spring:
  application:
    name: starter
  datasource:
    url: jdbc:mysql://localhost:3306/starter
    username: tester
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  web:
    resources:
      static-locations: file:src/main/resources/static/
server:
  port: 8081


jwt:
  secret: Exxmr6Bh7wASQRtdyZjjTM7Vo7cFbfpbEuWXsLnyp50=
  expiration: 86400000

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.pb.starter.model
  mapper-locations: classpath:mybatis/mapper/*.xml
#  config-location: classpath:mybatis-config.xml


springdoc:
  packages-to-scan: {
            com.pb.starter.subject.restController
  }
  cache:
    disabled: true
  api-docs:
    groups:
      enabled: true